### ISSUE TITLE
Directory names with colons interferes with cloning.

### ISSUE THREAD

**Issue by TuxEnthusiast** [Ajatt-Tools/kitsunekko-mirror#1]
https://stackoverflow.com/questions/78489191/why-does-git-not-allow-me-to-clone-this-repository

**Comment by tatsumoto-ren** [comment]
Windows is just a very bad operating system if it doesn't even allow you to have folders with colons in their names.

**Comment by tatsumoto-ren** [comment]
I'll try changing kitsunekko-tools to sanitize folder names before they're created. Until then, you can always use GNU/Linux to work around this issue.

**Comment by sappho192** [comment]
I've also solved this problem by cloning the repository on the WSL-Ubuntu.

**Comment by tatsumoto-ren** [comment]
The repository doesn't have any names with colons anymore so you should be able to clone it on any machine now.

**Comment by sappho192** [comment]
> The repository doesn't have any names with colons anymore so you should be able to clone it on any machine now.

I'm afraid it's not.

I tried to clone this repo on Windows+PowerShell and met those errors:

```
(base) PS D:\temp> git clone https://github.com/Ajatt-Tools/kitsunekko-mirror.git
Cloning into 'kitsunekko-mirror'...
remote: Enumerating objects: 106727, done.
remote: Counting objects: 100% (29503/29503), done.
remote: Compressing objects: 100% (26635/26635), done.
remote: Total 106727 (delta 2757), reused 29484 (delta 2740), pack-reused 77224
Receiving objects: 100% (106727/106727), 1.13 GiB | 17.48 MiB/s, done.
Resolving deltas: 100% (8506/8506), done.
error: invalid path 'subtitles/18-sai, Niizuma, Furin Shimasu./.kitsuinfo.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

When I googled above error, someone suggested setting following commands:
```
git config core.protectNTFS false
```

But still error occurs.
```
(base) PS D:\temp> cd .\kitsunekko-mirror\
(base) PS D:\temp\kitsunekko-mirror> git config core.protectNTFS false
(base) PS D:\temp\kitsunekko-mirror> git checkout -f HEAD
fatal: cannot create directory at 'subtitles/180 Byou de Kimi no Mimi o Shiawase ni Dekiru ka?': Invalid argument
(base) PS D:\temp\kitsunekko-mirror>
```

I've succeeded cloning the repo within the Ubuntu 22.04 on WSL2, but `18-sai, Niizuma, Furin Shimasu.` directory can't be accessed in Windows explorer. The directory can be accessed normally in Ubuntu(WSL2) by the way.

**Comment by tatsumoto-ren** [comment]
> error: invalid path 'subtitles/18-sai, Niizuma, Furin Shimasu./.kitsuinfo.json'

This name doesn't contain colons either. I suspect this is a different issue from this one.

**Comment by tatsumoto-ren** [comment]
I think this is because of the `?` symbol.
