### ISSUE TITLE
Windows: invalid path 'subtitles/18-sai, Niizuma, Furin Shimasu./.kitsuinfo.json'

### ISSUE THREAD

**Issue by FBenji2** [Ajatt-Tools/kitsunekko-mirror#2]
Hi!

The path 'subtitles/18-sai, Niizuma, Furin Shimasu./.kitsuinfo.json' is invalid on Windows systems, most likely due to the last character of the folder name "18-sai, Niizuma, Furin Shimasu." being a dot, which is apparently not allowed on windows. Can you please look into sanitizing folder names like that, like you did in issue #1?
Thanks!

**Comment by tatsumoto-ren** [comment]
> most likely due to the last character of the folder name "18-sai, Niizuma, Furin Shimasu." being a dot, which is apparently not allowed on windows. 

Are folders with dots at the end illegal on windows? If so, this is an issue with kitsunekko-tools.

**Comment by tatsumoto-ren** [comment]
I've renamed folders that had dots at the end. Feel free to close the issue if you think it's solved.

**Comment by FBenji2** [comment]
Yes, this one is fixed, thank you! I will open another one for the next one if you don't mind.
