### ISSUE TITLE
Windows: invalid path 'subtitles/Black Clover/ГuГЙГbГNГNГНБ[ГoБ[.S03E111.Ц\ВъЛН.Т╕ПуМИРэОQРэ!!.WEBRip.Netflix.ja[cc].srt'

### ISSUE THREAD

**Issue by FBenji2** [Ajatt-Tools/kitsunekko-mirror#3]
For a file in this anime, the subtitle file contains a backslash character which is not allowed (not allowed are: \ / : * ? " < > | ). Also I am not sure if the encoding for these file names are correct or not, looks weird.
![image](https://github.com/user-attachments/assets/b419d320-f3ec-4292-8e83-d6c5796cea3e)

**Comment by tatsumoto-ren** [comment]
Some files that originally were stored in archives were extracted and added to this repo. Sometimes atool can't detect the character encoding properly. I don't know why though. You can submit a PR that renames those files. Also, kitsunekko-tools needs a feature that checks externally added files, but I think it's not hard to implement it.

**Comment by tatsumoto-ren** [comment]
renamed black clover files in 1baeb776b99d1e8700f2c2985c28a835f6398f25

**Comment by FBenji2** [comment]
@tatsumoto-ren thank you! These are the remaining ones I found:

1. 'subtitles/Jigoku Sensei Nube/ТnНЦРцР╢В╩Б`В╫Б` МАПъФ┼Сц3Нь БuЛ░Х|В╠Й─ЛxВ▌БIБIЧdВ╡В╠КCВ╠У`РрБv (DVD 704x396 WMV9 q90).srt'
2. 'subtitles/Jigoku Sensei Nube/ТnНЦРцР╢В╩Б`В╫Б` Сц01Шb БuЛ░Х|В╠РVКwК· УфВ╠ЛSВ╠ОшБv (DVD 640x480 WMV9 q90).srt'
3. 'subtitles/Jigoku Sensei Nube/ТnНЦРцР╢В╩Б`В╫Б` Сц03Шb БuВдВэВ│ШbВ═ВтВ▀ВчВъВ╚Вв ВиВ╡ВсВ╫ВшЧdЙЎБEЛ░Х|В╠М▄ЦЗРуБIБv (DVD 640x480 WMV9 q90).srt'
4. 'subtitles/Jigoku Sensei Nube/ТnНЦРцР╢В╩Б`В╫Б` Сц12Шb БuЛ░Х|В╠ЙУСлБIЛSЦхУ╗В╠УфБv (DVD 640x480 WMV9 q90).srt'
5. 'subtitles/Jigoku Sensei Nube/ТnНЦРцР╢В╩Б`В╫Б` Сц14Шb БuЛ╜ОqВк2РlБIБHГhГbГyГЛГQГУГKБ[В╠Л░Х|Бv (DVD 640x480 WMV9 q90).srt'
6. 'subtitles/Jigoku Sensei Nube/ТnНЦРцР╢В╩Б`В╫Б` Сц30Шb БuХ·Й█МуВ╠Л░Х|БIСЦВщУёЛ{ЛрОЯШYСЬБIБIБv (DVD 640x480 WMV9 q90).srt'
7. 'subtitles/Jigoku Sensei Nube/ТnНЦРцР╢В╩Б`В╫Б` Сц31Шb БuТNВ╔ВрМ╛ВжВ╚ВвЦ┌Л╩В╠Л░Х|БIБIУVН╦ГoГCГIГКГjГXГgВ╠СхН▀Бv (DVD 640x480 WMV9 q90).srt'
8. 'subtitles/Juuni Kokuki/(BD)╩о╢■╣·╙Ы ╡┌41╘Тб╕Ц|д╬║г╔ё ╬ўд╬Ьц║гбб╥╗╒┬б╣(1440x1080 x264-10bpp flac).jap.ass'
9. 'subtitles/Juuni Kokuki/(BD)╩о╢■╣·╙Ы ╡┌42╘Тб╕Ц|д╬║г╔ё ╬ўд╬Ьц║гбб╢■╒┬б╣(1440x1080 x264-10bpp flac).jap.ass'
10. 'subtitles/Juuni Kokuki/(BD)╩о╢■╣·╙Ы ╡┌43╘Тб╕Ц|д╬║г╔ё ╬ўд╬Ьц║гбб╚¤╒┬б╣(1440x1080 x264-10bpp flac).jap.ass'
11. 'subtitles/Juuni Kokuki/(BD)╩о╢■╣·╙Ы ╡┌44╘Тб╕Ц|д╬║г╔ё ╬ўд╬Ьц║гбб╓╒╒┬б╣(1440x1080 x264-10bpp flac).jap.ass'
12. 'subtitles/Juuni Kokuki/(BD)╩о╢■╣·╙Ы ╡┌45╘Тб╕Ц|д╬║г╔ё ╬ўд╬Ьц║гбб╫к╒┬б╣(1440x1080 x264-10bpp flac).jap.ass'
13. 'subtitles/Kidou Keisatsu Patlabor/[ГAГjГБ] Л@УоМxО@ГpГgГМГCГoБ[ ON TELEVISION Сц23Шb БuНБК╤Й╘ГМГ|Б[ГgБv (BLU-RAY x264 1440x1080).srt'
14. 'subtitles/Konjiki no Gash Bell!!/extra/ЛрРFВ╠ГKГbГVГЕГxГЛ!!.S01E24.Сц24Шb.ОйЧRВ╠Ч╖РlГAГ|ГН.WEBRip.Netflix.ja[cc].srt'
15. 'subtitles/Kyou kara Ore wa!!/НбУ·ВйВчЙ┤В═!!-ГVБ[ГYГУ1-9-ГПГУГXБEГAГ|ГУБEГAБEГ^ГCГАБEГCГУБEРчЧt_ja.srt'
16. 'subtitles/No Guns Life/ГmБ[БEГKГУГYБEГЙГCГt Сц01Шb БuЦ\СЦКgТгО╥Бv (TBS) [2019-10-11_0128].jap.ass'
17. 'subtitles/Uzaki-chan wa Asobitai!/2020071021302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#&NoBreak;01.ass'
18. 'subtitles/Uzaki-chan wa Asobitai!/2020071721302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#&NoBreak;02.ass'
19. 'subtitles/Uzaki-chan wa Asobitai!/2020072421302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#&NoBreak;03.ass'
20. 'subtitles/Uzaki-chan wa Asobitai!/2020073121302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#04.ass'
21. 'subtitles/Uzaki-chan wa Asobitai!/2020080721302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#05.ass'
22. 'subtitles/Uzaki-chan wa Asobitai!/2020081421302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#06.ass'
23. 'subtitles/Uzaki-chan wa Asobitai!/2020082121302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#07.ass'
24. 'subtitles/Uzaki-chan wa Asobitai!/2020082821302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#08.ass'
25. 'subtitles/Uzaki-chan wa Asobitai!/2020090421302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#09.ass'
26. 'subtitles/Uzaki-chan wa Asobitai!/2020091121302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#10.ass'
27. 'subtitles/Uzaki-chan wa Asobitai!/2020091821302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#11.ass'
28. 'subtitles/Uzaki-chan wa Asobitai!/2020092521302200-В`ВsБ|Вw-ЙFНшВ┐ВсВёВ═ЧVВ╤В╜Вв!#12.ass'

**Comment by tatsumoto-ren** [comment]
I renamed the files you listed.

**Comment by FBenji2** [comment]
Thanks, I closed the issue. Now the repo is checked out on windows.

**Comment by tatsumoto-ren** [comment]
Next time please avoid running Windows. Windows is proprietary software with malicious functionalities. 

https://www.fsf.org/windows

**Comment by FBenji2** [comment]
If this is your recommendation for this repo, I suggest you also include it in the readme, because it is not clear from it.

**Comment by tatsumoto-ren** [comment]
We recommend running GNU to everyone who is learning Japanese with the AJATT method and reading our website, so I thought it wasn't necessary to repeat the same information in this repo.

See https://tatsumoto.neocities.org/blog/do-i-have-to-run-gnu
